language: node_js

node_js:
- 10

script:
- |
    if [ "$TEST_TYPE" = test ]; then
      npm test
    else
      npm run $TEST_TYPE
    fi
env:
  matrix:
  - TEST_TYPE=lint
  - TEST_TYPE=test
  - TEST_TYPE=coverage
